const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let points=+(localStorage.tw2_points||0),premium=localStorage.tw2_premium==='1',name=localStorage.tw2_name||'Future Trades Professional';
const lessons={HVAC:[['01','Safety, tools, and PPE','Free'],['02','Electrical fundamentals and meter use','Free'],['03','Thermostats, transformers, contactors, relays','Premium'],['04','Motors, capacitors, airflow, refrigeration basics','Premium'],['05','No-cooling service call simulation','Premium']],Electrical:[['01','Electrical safety and safe work habits','Free'],['02','Voltage, current, resistance, and Ohm’s Law','Free'],['03','Residential circuits, switches, receptacles','Premium'],['04','Panels, breakers, grounding and bonding','Premium'],['05','Dead-circuit troubleshooting simulation','Premium']],Plumbing:[['01','Safety, tools, materials, fittings','Free'],['02','Water supply, pressure, valves, fixtures','Free'],['03','Drain, waste, and vent fundamentals','Premium'],['04','Water heaters, pumps, service diagnostics','Premium'],['05','Low-pressure troubleshooting simulation','Premium']]};
function save(){localStorage.tw2_points=points;localStorage.tw2_premium=premium?'1':'0';localStorage.tw2_name=name}
function done(){return Object.keys(localStorage).filter(k=>k.startsWith('tw2_done_'))}
function ui(){ $('#studentName').textContent=name;$('#points').textContent=points;$('#doneCount').textContent=done().length;$('#challengeCount').textContent=localStorage.tw2_challenge?'1':'0';$('#level').textContent=Math.max(1,Math.floor(points/150)+1);[['HVAC','h'],['Electrical','e'],['Plumbing','p']].forEach(([t,p])=>{let c=done().filter(k=>k.startsWith('tw2_done_'+t+'_')).length,v=Math.round(c/5*100);$('#'+p+'pct').textContent=v+'%';$('#'+p+'bar').style.width=v+'%'})}
ui();$('#menu').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));
function open(id){$(id).classList.add('open')}function close(){ $$('.modal').forEach(m=>m.classList.remove('open'))}$$('.close').forEach(b=>b.onclick=close);$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)close()});
$('#profileBtn').onclick=()=>open('#profileModal');$('#saveProfile').onclick=()=>{let v=$('#nameInput').value.trim();if(v)name=v;save();ui();close()};
function academy(t){$('#tradeLabel').textContent=t.toUpperCase()+' ACADEMY';$('#tradeTitle').textContent=t+' Learning Path';$('#lessonList').innerHTML=lessons[t].map(([n,title,tier])=>{let key='tw2_done_'+t+'_'+n,d=localStorage[key]==='1',lock=tier==='Premium'&&!premium;return `<div class="lesson"><div><small>MODULE ${n}<span class="tag ${tier==='Free'?'free':'premium'}">${tier}</span></small><b>${title}</b><p>${d?'Completed':lock?'Premium module':'Available now'}</p></div><button data-key="${key}" data-lock="${lock}" ${d?'disabled':''}>${d?'Completed ✓':lock?'Unlock':'Complete'}</button></div>`}).join('');$$('#lessonList button').forEach(b=>b.onclick=()=>{if(b.dataset.lock==='true'){close();open('#upgradeModal');return}if(!localStorage[b.dataset.key]){localStorage[b.dataset.key]='1';points+=25;save();ui();b.textContent='Completed ✓';b.disabled=true}});open('#academyModal')}
$$('.open').forEach(b=>b.onclick=()=>academy(b.dataset.trade));$('#upgrade').onclick=()=>open('#upgradeModal');$('#demoUnlock').onclick=()=>{premium=true;save();close();alert('Premium demo unlocked on this device.')};$('#org').onclick=()=>alert('Production version: this would open a school/employer demo request form.');
$$('#choices button').forEach(b=>b.onclick=()=>{$$('#choices button').forEach(x=>{x.disabled=true;if(x.dataset.c==='1')x.classList.add('correct')});if(b.dataset.c==='1'){if(!localStorage.tw2_challenge){localStorage.tw2_challenge='1';points+=100;save();ui()}$('#feedback').innerHTML='<b>Correct.</b> Control voltage is reaching the contactor coil. Check whether the contactor is pulling in and passing power to the load.'}else{b.classList.add('wrong');$('#feedback').innerHTML='<b>Not the best next step.</b> Use the measurements already given before replacing unrelated parts.'}});